### ISSUE TITLE
Tutor-Course Shortcode html issue

### ISSUE THREAD

**Issue by pranjalvatsa** [themeum/tutor#4]
I have started using the Tutor LMS plugin and must say it really makes life easy.

I have encountered a UI error that I am not able to fix. 

I have 2 courses as of now and want to list them using the "[tutor-course]" shortcode. But its giving some HTML issue.

Please see the UI below (2nd course comes below the 1st). Also attaching the HTML output. As you can see from the HTML, the 2nd course <div> is embedded inside the 1st div with tutor-course-col-3 class. Here lies the problem.

![Screen Shot 2020-04-17 at 8 38 01 pm](https://user-images.githubusercontent.com/10488068/79605825-3a8bff00-810e-11ea-8b6d-e4a2ceb0e875.png)
![Screen Shot 2020-04-17 at 8 37 40 pm](https://user-images.githubusercontent.com/10488068/79605834-3d86ef80-810e-11ea-802f-466afc3d45a7.png)

**Comment by themeum** [comment]
Hello,

We've received your email! Someone from our team will get back to you as
soon as possible.

Please note that we are receiving a massive volume of emails during the
pandemic. All of the team members are working remotely from their homes.
Because of limited resources and extra workload, there might be some delay
in our response. We expect your patience and cooperation.

If you are facing any issue with any of our product, please check the
following-
1. You have the latest version of PHP. Any PHP version less than 7.3 might
cause an issue.
2. You have the latest version of WordPress.
3. You have checked for theme and plugin conflicts.

*PS: Saturday and Sunday are our weekend.*

Thank you!
{#HS:1156830829-28243#}
