### ISSUE TITLE
How is the API going on?

### ISSUE THREAD

**Issue by gustavosilva-gss** [themeum/tutor#5]
https://wordpress.org/support/topic/database-structure-and-api-question/
In this question is said that you had plans on creating an API on mid-2020. How is that going?

**Comment by themeum** [comment]
Hello,

We've received your email! Someone from our team will get back to you as
soon as possible.

Please note that we are receiving a massive volume of emails during the
pandemic. All of the team members are working remotely from their homes.
Because of limited resources and extra workload, there might be some delay
in our response. We expect your patience and cooperation.

If you are facing any issue with any of our product, please check the
following-
1. You have the latest version of PHP. Any PHP version less than 7.3 might
cause an issue.
2. You have the latest version of WordPress.
3. You have checked for theme and plugin conflicts.

*PS: Saturday and Sunday are our weekend.*

Thank you!
{#HS:1145917417-26521#}

**Comment by themeum** [comment]
Hello,

We've received your email! Someone from our team will get back to you as
soon as possible.

Please note that we are receiving a massive volume of emails during the
pandemic. All of the team members are working remotely from their homes.
Because of limited resources and extra workload, there might be some delay
in our response. We expect your patience and cooperation.

If you are facing any issue with any of our product, please check the
following-
1. You have the latest version of PHP. Any PHP version less than 7.3 might
cause an issue.
2. You have the latest version of WordPress.
3. You have checked for theme and plugin conflicts.

*PS: Saturday and Sunday are our weekend.*

Thank you!
{#HS:1146383410-26604#}
