### ISSUE TITLE
Buying courses with amazon pay does not enroll students

### ISSUE THREAD

**Issue by Vinschni** [themeum/tutor#52]
Hello together,
using woocommerce as monetarization works fine for all payment methods i tested ( six different ones) but when using amazon pay the payment sucessfully finished in woocommerce but does not lead enroll the user in the course he/she brought with tutor lms.

Can you give me a hint what the reason could be?
* I'm guessing `woocommerce_new_order_item` is not fired with amazon pay, but I do not know how to confirm that.
* I validated the enrollment posts in the database are actually missing by that query:
```
SELECT * FROM `wp_posts` WHERE `post_status` LIKE "completed"`
```

I'm using c430863

**Comment by mkasprz** [comment]
Just a guess, but I think I had a similar issue. After making payment using some payment method an order status has not been changing to "Completed", but been rather staying "Processing". I used [WunderAutomation](https://wordpress.org/plugins/wunderautomation/) plugin to automatically change the status of such orders.

I also think that if the problem is about order status not changing to "Completed" it's not really an issue with Tutor, but rather this specific payment gateway plugin or WooCommerce.

**Comment by Vinschni** [comment]
Dear @mkasprz that is correct. Manually setting the order status in WooCommerce to "Completed" triggered the enrollment.

**Comment by mkasprz** [comment]
I'm glad it helped! Thanks for letting me know.
