### ISSUE TITLE
Login button on course page redirects to Student Dashboard

### ISSUE THREAD

**Issue by VariyaKrupal** [themeum/tutor#6]
The login form/button on the course page is redirecting to the student dashboard instead of the course page itself.

I fixed it by changing the content of else condition on line 69 with the following line of codes in classes/FormHandler.php 

`                        else {
                              //Redirect page
                                $redirect_page = tutils()->array_get('redirect_to', $_REQUEST);
                                if ( ! $redirect_page){
                                        $redirect_page = tutor_utils()->tutor_dashboard_url();
                                }
                                tutor_redirect_back(apply_filters('tutor_login_redirect_url', $redirect_page));
                        }
`

**Comment by themeum** [comment]
Hello,

We've received your email! Someone from our team will get back to you as
soon as possible.

Please note that we are receiving a massive volume of emails during the
pandemic. All of the team members are working remotely from their homes.
Because of limited resources and extra workload, there might be some delay
in our response. We expect your patience and cooperation.

If you are facing any issue with any of our product, please check the
following-
1. You have the latest version of PHP. Any PHP version less than 7.3 might
cause an issue.
2. You have the latest version of WordPress.
3. You have checked for theme and plugin conflicts.

*PS: Saturday and Sunday are our weekend.*

Thank you!
{#HS:1148253726-26922#}

**Comment by VariyaKrupal** [comment]
Seems like this got fixed in the latest update :+1:
